version: '3.9'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - proyectos
            - modulos
            - funciones
        ports:
            - "8080:80"
    sqlite3:
        container_name: sqlite3_container
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./sqlite3:/root/db/
        ports:
            - '9000:9000'
        modulosrt: unless-stopped
        
    proyectos:
        build: ./proyectos
        volumes:
           - ".:/sqlite3:rw"

    modulos:
        build: ./modulos
        volumes:
            - ".:/sqlite3:rw"

    funciones:
        build: ./funciones
        volumes:
            - ".:/sqlite3:rw"
